format = """\
    $directory\
    $hostname\
    $username\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $kubernetes\
    $aws\
    $terraform\
    $python\
    $custom\
    $line_break\
    $character\
"""

[username]
show_always  = true
format = "ğŸŒ [$user]($style) "
style_user = "bold black"

[hostname]
ssh_only = false
style = "bold red"
format = "ğŸ£ [$hostname]($style) "

[git_branch]
symbol = "ğŸ˜ "
style = "bold yellow"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"

[character]
success_symbol = "[â¯â¯â¯](bold green)"

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold green"
format = "[$path]($style)[$read_only]($read_only_style) "

[golang]
style = "bold black"
format = "[$symbol$version]($style) "

[dart]
style = "bold black"
format = "[$symbol$version]($style) "

[python]
style = "bold black"
format = "[$symbol$version]($style) "

[nodejs]
style = "bold black"
format = "[$symbol$version]($style) "
symbol = "ğŸ¢ "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\) )]($style) '
style = "bold cyan"

[gcloud]
style = "bold black"
symbol = "ğŸ˜ "
format = '[$symbol$account(\($region\))]($style) '

[aws]
style = "bold black"
symbol = "ğŸŒ´ "
format = '[$symbol$profile(\($region\))]($style) '

[terraform]
style = "bold black"
format = "[$symbol$workspace]($style) "

[time]
disabled = false
format = "ğŸ•˜ [$time]($style) "
style = "bold black"
