prompt_order = [
    "hostname",
    "username",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "golang",
    "dart",
    "python",
    "nodejs",
    "kubernetes",
    "docker_context",
    "package",
    "aws",
    "gcloud",
    "env_var",
    "memory_usage",
    "cmd_duration",
    "jobs",
    "battery",
    "time",
    "custom",
    "line_break",
    "character",
]

[hostname]
ssh_only = false
style = "bold red"

[username]
show_always  = true

[git_branch]
symbol = "ğŸ£ "
style = "bold black"

[character]
symbol = "â¯â¯â¯"

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold green"

[kubernetes]
disabled = false

[nodejs]
symbol = "ğŸ¢ "
style = "bold blue"
