format = """\
    $hostname\
    $username\
    $directory\
    $time\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $golang\
    $dart\
    $python\
    $nodejs\
    $package\
    $aws\
    $gcloud\
    $terraform\
    $kubernetes\
    $custom\
    $line_break\
    $character\
"""

[username]
show_always  = true

[hostname]
ssh_only = false
style = "bold red"

[git_branch]
symbol = "ğŸ£ "
style = "bold red"

[character]
symbol = "â¯â¯â¯"

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold green"

[golang]
style = "bold yellow"

[dart]
style = "bold yellow"

[python]
style = "bold yellow"

[nodejs]
symbol = "ğŸ¢ "
style = "bold yellow"

[kubernetes]
disabled = false
style = "bold green"

[gcloud]
style = "bold black"
symbol = "ğŸ˜ "

[aws]
style = "bold black"

[terraform]
style = "bold black"

[time]
disabled = false
style = "bold black"


